name: Cascading branch merge on commit

on:
  push:
    branches:
      - release/**
jobs:
  release-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
        with:
          repository: discoveryedu/github-actions-release-automerge
          ref: refs/heads/main
          ssh-key: ${{secrets.READ_ONLY_RELEASE_AUTOMERGE}}
          persist-credentials: false
          path: ./.github/actions/release-automerge
      - name: Run action
        uses: ./.github/actions/release-automerge
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
